<?php
$products = [
    1 => [
        'id' => 1,
        'name' => 'MiraclWatch™ Pro Ultra MAX',
        'tagline' => 'La montre qui change TOUT',
        'price' => 29.99,
        'fake_original_price' => 999.99,
        'cart_price' => 79.99, // bait & switch
        'image' => 'assets/images/product_watch.png',
        'rating' => 4.9,
        'reviews' => 4872,
        'stock' => 2,
        'category' => 'Tech',
        'description' => 'La MiraclWatch™ Pro Ultra MAX utilise notre technologie quantico-IA brevetée pour surveiller votre santé, prédire l\'avenir et peut-être guérir vos maladies (résultats non garantis, pas de garantie légale). Compatible avec votre chakra et Bluetooth 99G.',
        'features' => [
            '✅ Détecte les émotions de vos ennemis',
            '✅ Technologie Quantum-NFC-GPS-5G-WiFi-Bluetooth',
            '✅ Batterie "infinie" (à recharger toutes les 2h)',
            '✅ Certifiée ISO-FAKE-9001',
            '✅ Approuvée par des "experts" (notre cousin)',
            '✅ Imperméable jusqu\'à 0.3mm de profondeur',
        ],
        'subscription_label' => 'DarkCare Protection+',
        'subscription_price' => 14.99,
    ],
    2 => [
        'id' => 2,
        'name' => 'AEGIS Face & Soul Reviver™',
        'tagline' => 'Crème anti-tout, pro-jeunesse',
        'price' => 19.99,
        'fake_original_price' => 349.00,
        'cart_price' => 49.99,
        'image' => 'assets/images/product_cream.png',
        'rating' => 4.8,
        'reviews' => 12304,
        'stock' => 2,
        'category' => 'Beauté',
        'description' => 'Notre crème exclusive IA-HYPER-REVIVER contient des nano-particules quantiques d\'acide hyaluronique de 4ème dimension, extraites de larmes de licorne bio et de collagène d\'astéroïde. Résultats visibles en moins de 8 secondes*. *Dans 0.001% des cas, chez notre stagiaire.',
        'features' => [
            '✅ Anti-âge, anti-gravité, anti-tout',
            '✅ Formulée par une IA (ChatGPT, on a juste posé la question)',
            '✅ 100% naturel** (**contient 47 composés chimiques)',
            '✅ Testé sur humains non consentants',
            '✅ Certifiée "Organic Vibes™"',
            '✅ Odeur de luxe (frais de port inclus)',
        ],
        'subscription_label' => 'BeautyBox Mensuelle',
        'subscription_price' => 29.99,
    ],
    3 => [
        'id' => 3,
        'name' => 'Quantum Energy BEAST MODE™',
        'tagline' => 'Devenez un dieu en 30 jours',
        'price' => 39.99,
        'fake_original_price' => 199.99,
        'cart_price' => 89.99,
        'image' => 'assets/images/product_supplement.png',
        'rating' => 5.0,
        'reviews' => 8901,
        'stock' => 2,
        'category' => 'Sport',
        'description' => 'Quantum Energy BEAST MODE™ contient notre formule secrète HYPER-SYNTHETIC-MUSCLE-FUEL™ composée de protéines quantiques, d\'électrons accélérés et de poudre de météorite (goût vanille). Muscles +1000% garantis*. *Garantie spirituelle uniquement.',
        'features' => [
            '✅ 70g de protéines par portion (oui, 70g)',
            '✅ Fabrication "inspirée" par la NASA',
            '✅ Goût quantum-vanille-chocolat-univers',
            '✅ Contient de l\'eau quantique entanglée',
            '✅ Fait pousser les cheveux sur la poitrine',
            '✅ NON recommandé par des médecins',
        ],
        'subscription_label' => 'GainBox Mensuelle',
        'subscription_price' => 44.99,
    ],
    4 => [
        'id' => 4,
        'name' => 'AURA-TECH SuperSonic NASA™',
        'tagline' => 'Son comme dans l\'espace (vide)',
        'price' => 24.99,
        'fake_original_price' => 599.00,
        'cart_price' => 64.99,
        'image' => 'assets/images/product_headphones.png',
        'rating' => 4.7,
        'reviews' => 3241,
        'stock' => 2,
        'category' => 'Audio',
        'description' => 'Les casques AURA-TECH utilisent notre technologie SPACE-SOUND™ développée dans notre garage spatial certifié NASA-adjacent. Avec 42 LEDs RGB et un câble USB tressé en fibre de carbone recyclé de fusée. Son cristallin jusqu\'à 20Hz (comme tous les casques).',
        'features' => [
            '✅ Technologie NASA-adjacent™',
            '✅ 42 LEDs RGB pour mieux entendre',
            '✅ Câble USB + Jack (pour les appareils sans jack)',
            '✅ Réduction de bruit "quantique"',
            '✅ Compatible PS1, PS2, PS6, Xbox, Dreamcast',
            '✅ Garantie 7 jours (si pas ouvert)',
        ],
        'subscription_label' => 'SoundCloud Premium Forcé',
        'subscription_price' => 9.99,
    ],
    5 => [
        'id' => 5,
        'name' => 'Sac PARISian Style™ GG Inspiration',
        'tagline' => 'Inspiré par les grandes maisons*',
        'price' => 49.99,
        'fake_original_price' => 2400.00,
        'cart_price' => 129.99,
        'image' => 'assets/images/product_bag.png',
        'rating' => 4.6,
        'reviews' => 6723,
        'stock' => 2,
        'category' => 'Mode',
        'description' => 'Notre sac PARISian Style™ est "inspiré" des plus grandes maisons de couture (on s\'est promenés devant leurs vitrines). Fabriqué en vinyl haute-resistance (plastique premium), avec fermoir en alliage doré (laiton). Le logo GG? C\'est nos initiales. Garantie Gilles Grunberg.',
        'features' => [
            '✅ "Inspiré" (pas copié, inspiré)',
            '✅ Vinyl premium ultra-résistant à la pluie légère',
            '✅ Logo exclusif GG (Gilles, notre fondateur)',
            '✅ Livré dans un sac en plastique signature',
            '✅ Vu dans un magazine (que l\'on a créé)',
            '✅ Disponible en noir (et c\'est tout)',
        ],
        'subscription_label' => 'Fashion Box Mensuelle',
        'subscription_price' => 24.99,
    ],
    6 => [
        'id' => 6,
        'name' => 'ULTRA GAMER ChaoThrone™ 9000',
        'tagline' => '500% plus ergonomique*',
        'price' => 89.99,
        'fake_original_price' => 1299.00,
        'cart_price' => 199.99,
        'image' => 'assets/images/product_chair.png',
        'rating' => 4.5,
        'reviews' => 2187,
        'stock' => 2,
        'category' => 'Gaming',
        'description' => 'La ChaoThrone™ 9000 est le summum du gaming. Équipée de RGB partout (même sous les accoudoirs), d\'un cuir synthétique qui respire (les trous font du bruit), et d\'un design inspiré par F1, Batmobile et notre ancien canapé. *500% plus ergonomique que s\'asseoir par terre.',
        'features' => [
            '✅ RGB sur 360° (le sol aussi)',
            '✅ Dossier réglable (entre 90° et 91°)',
            '✅ Repose-pieds inclus (un peu bancal)',
            '✅ Cuir synthétique premium (se décolle après 3 jours)',
            '✅ Supporte jusqu\'à 50kg (we recommend < 49kg)',
            '✅ Assemblage "DIY" (bonne chance)',
        ],
        'subscription_label' => 'GamerPass Mensuel',
        'subscription_price' => 19.99,
    ],
];

function getProduct($id) {
    global $products;
    return $products[$id] ?? null;
}

function getAllProducts() {
    global $products;
    return $products;
}
?>
